### ISSUE TITLE
Error: The requested dataset URL was not found (HTTP error 404)

### ISSUE THREAD

**Issue by tubabucak** [SantanderMetGroup/climate4R.UDG#2]
Dear all,

This code was working yesterday but somehow now it gives this error. I wonder if this is temporary issue?

library(loadeR)
library(transformeR)
library(visualizeR)
library(downscaleR)
library(climate4R.value)
library(climate4R.UDG)

When I run the code below, it works well.

climate4R.UDG::loginUDG(username = "XXXXXX", password = "XXXXXX")

_2020-07-22 10:22:26] Setting credentials...
[2020-07-22 10:22:26] Success!
Go to <http://www.meteo.unican.es/udg-tap/home> for details on your authorized groups and datasets_

However loadGridData could not access the dataset URL. Any idea of the possible reason?

vars <- c("tas","ta@500","ta@700", "ta@850",
          "hus@500","hus@850","z@500")

data("PRUDENCEregions", package = "visualizeR")
bb <- PRUDENCEregions["IP"]@bbox
lon <- bb[1,]; lat <- bb[2,]
grid.list5 <- lapply(vars, function(x) {
  loadGridData(dataset = "ECMWF_ERA-Interim-ESD",
               var = x,
               lonLim = lon,
               latLim = lat,
               years = 1979:2008)
}
)

It gives error:

NOTE: Accessing harmonized data from a public UDG dataset
[2020-07-22 10:23:07] Defining harmonization parameters for variable "psl"
[2020-07-22 10:23:07] Opening dataset...
 Error: The requested dataset URL was not found (HTTP error 404

**Comment by zequihg50** [comment]
Hi @tubabucak , could you confirm that it's working now?

**Comment by tubabucak** [comment]
Now it says:
Error: Requested URL not found
The problem may be momentary.

Ezequiel Cimadevilla Alvarez <notifications@github.com>, 22 Tem 2020 Çar,
12:32 tarihinde şunu yazdı:

**Comment by zequihg50** [comment]
Could you update `climate4R.UDG` as follows?

```
library(devtools)
install_github("SantanderMetGroup/climate4R.UDG@devel")
```

I needed to fix couple of things there. It should work after the update but if it continuous to fail, would you attach the output of `sessionInfo()` please?

**Comment by tubabucak** [comment]
Thank you very much. When I try to install climate4R.UDG, it requires the
update of rJava as well and at the end I found myself updating R to 4.0.2
to be able to install rJava and other packages as well. There were some
problems regarding java and I am trying to solve them. I will let you know
if I could manage it.

Ezequiel Cimadevilla Alvarez <notifications@github.com>, 22 Tem 2020 Çar,
14:38 tarihinde şunu yazdı:

**Comment by tubabucak** [comment]
Now it is working! Thank you very much for your quick response again.
